app:
  Address: "0.0.0.0:8000"

database:
  driver: "postgres"
  host: "db.arksmzmcvccxmlxobtsj.supabase.co"
  port: "5432"
  username: "postgres"
  password: "bY3RRfgK1Ow53o5s"
  database: "postgres"

redis:
  host: "localhost"
  port: "6379"
  password: ""